# Generated by Django 5.2.12 on 2026-03-09 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('localized_name', models.CharField(max_length=100)),
                ('primary_attr', models.CharField(blank=True, default='', max_length=10)),
                ('attack_type', models.CharField(blank=True, default='', max_length=20)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('img_url', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'db_table': 'heroes',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('duration_seconds', models.IntegerField()),
                ('game_mode', models.IntegerField(default=0)),
                ('lobby_type', models.IntegerField(default=0)),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('radiant_score', models.IntegerField(default=0)),
                ('dire_score', models.IntegerField(default=0)),
                ('radiant_win', models.BooleanField(null=True)),
                ('first_blood_time', models.IntegerField(blank=True, null=True)),
                ('patch', models.IntegerField(blank=True, null=True)),
                ('radiant_gold_adv', models.JSONField(blank=True, null=True)),
                ('radiant_xp_adv', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
                ('pick_order', models.IntegerField()),
                ('is_pick', models.BooleanField()),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.hero')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='matches.match')),
            ],
            options={
                'db_table': 'match_draft',
            },
        ),
        migrations.CreateModel(
            name='HeroBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('percentiles', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='matches.hero')),
            ],
            options={
                'db_table': 'hero_benchmarks',
                'unique_together': {('hero', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='PlayerHeroStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('avg_kda', models.FloatField(default=0.0)),
                ('avg_gpm', models.FloatField(default=0.0)),
                ('avg_xpm', models.FloatField(default=0.0)),
                ('avg_hero_damage', models.FloatField(default=0.0)),
                ('avg_tower_damage', models.FloatField(default=0.0)),
                ('avg_last_hits', models.FloatField(default=0.0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.hero')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_stats', to='players.player')),
            ],
            options={
                'db_table': 'player_hero_stats',
                'unique_together': {('player', 'hero')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_slot', models.IntegerField()),
                ('is_radiant', models.BooleanField()),
                ('win', models.BooleanField()),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('kda', models.FloatField(default=0.0)),
                ('last_hits', models.IntegerField(default=0)),
                ('denies', models.IntegerField(default=0)),
                ('gold_per_min', models.IntegerField(default=0)),
                ('xp_per_min', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('hero_damage', models.IntegerField(default=0)),
                ('hero_healing', models.IntegerField(default=0)),
                ('tower_damage', models.IntegerField(default=0)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('lane_role', models.IntegerField(blank=True, null=True)),
                ('lane_efficiency', models.FloatField(blank=True, null=True)),
                ('camps_stacked', models.IntegerField(default=0)),
                ('obs_placed', models.IntegerField(default=0)),
                ('sen_placed', models.IntegerField(default=0)),
                ('actions_per_min', models.IntegerField(default=0)),
                ('stuns_seconds', models.FloatField(default=0.0)),
                ('neutral_kills', models.IntegerField(default=0)),
                ('items_final', models.JSONField(blank=True, default=dict)),
                ('purchase_log', models.JSONField(blank=True, default=list)),
                ('gold_timeline', models.JSONField(blank=True, default=list)),
                ('xp_timeline', models.JSONField(blank=True, default=list)),
                ('lh_timeline', models.JSONField(blank=True, default=list)),
                ('ability_upgrades', models.JSONField(blank=True, default=list)),
                ('damage_targets', models.JSONField(blank=True, default=dict)),
                ('runes_log', models.JSONField(blank=True, default=list)),
                ('buyback_log', models.JSONField(blank=True, default=list)),
                ('party_size', models.IntegerField(blank=True, null=True)),
                ('rank_tier', models.IntegerField(blank=True, null=True)),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_performances', to='matches.hero')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_performances', to='players.player')),
            ],
            options={
                'db_table': 'player_matches',
                'indexes': [models.Index(fields=['player', 'hero', 'lane_role'], name='player_matc_player__40b1e2_idx')],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
