# Generated by Django 5.2.12 on 2026-03-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(db_index=True, unique=True)),
                ('steam_id_64', models.BigIntegerField(blank=True, null=True)),
                ('personaname', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('rank_tier', models.IntegerField(blank=True, null=True)),
                ('leaderboard_rank', models.IntegerField(blank=True, null=True)),
                ('estimated_mmr', models.IntegerField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_synced_match_id', models.BigIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
